# Reading data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
PATH = os.path.join("data", "train.csv")
data = pd.read_csv(PATH)

In [3]:
data["gender"] = data["gender"].map({"male": 1, "female": 0})

In [4]:
data["age_60_and_above"] = data["age_60_and_above"].map({"Yes": 1, "No": 0})

In [5]:
data["test_indication"] = data["test_indication"].map({"Contact with confirmed": 2, "Abroad": 1, "Other": 0})

In [6]:
data.head()

test_date  cough  fever  sore_throat  shortness_of_breath  head_ache  \
0  2020-03-22    1.0    0.0            0                    0          0   
1  2020-03-22    1.0    1.0            0                    0          0   
2  2020-03-22    0.0    1.0            0                    0          0   
3  2020-03-22    1.0    1.0            0                    0          0   
4  2020-03-22    1.0    0.0            0                    0          0   

   corona_result  age_60_and_above  gender  test_indication  
0            0.0                 0     1.0                0  
1            0.0                 0     1.0                1  
2            0.0                 1     1.0                2  
3            1.0                 1     1.0                1  
4            0.0                 1     0.0                2

In [7]:
data["corona_result"].value_counts()

0.0    101841
1.0      9158
Name: corona_result, dtype: int64

In [8]:
y = data["corona_result"].fillna(-1)
X = data.drop(["test_date", "corona_result"], axis = 1).fillna(-1)

In [9]:
X["gender"].unique()

array([ 1.,  0., -1.])

In [10]:
y.unique()

array([ 0.,  1., -1.])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 11)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((78641, 8), (33704, 8), (78641,), (33704,))

In [14]:
X_train["gender"].unique()

array([ 1.,  0., -1.])

# Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegressionCV

In [15]:
Cs = [20, 21, 22, 23]
logit = LogisticRegressionCV(Cs = Cs, class_weight = "balanced", \
                             n_jobs = -1, verbose = 5, random_state = 11)

In [16]:
logit.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:    4.8s remaining:    7.3s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    4.9s finished


LogisticRegressionCV(Cs=[20, 21, 22, 23], class_weight='balanced', cv=None,
                     dual=False, fit_intercept=True, intercept_scaling=1.0,
                     l1_ratios=None, max_iter=100, multi_class='auto',
                     n_jobs=-1, penalty='l2', random_state=11, refit=True,
                     scoring=None, solver='lbfgs', tol=0.0001, verbose=5)

In [17]:
logit.C_

array([20, 20, 20])

In [18]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, logit.predict(X_test))

0.73685615950629

In [19]:
y_test.value_counts()

 0.0    30569
 1.0     2727
-1.0      408
Name: corona_result, dtype: int64

# Random forest

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rf = RandomForestClassifier(oob_score = True, n_jobs = -1, verbose = 10, class_weight = "balanced")

params = {
    "max_depth": np.arange(6, 12)
}

rf = GridSearchCV(rf, params, n_jobs = -1, verbose = 10)

In [22]:
rf.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    6.5s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:   10.8s
[Parallel(n_jobs=-1)]: Done  19 out of  30 | elapsed:   16.7s remaining:    9.6s
[Parallel(n_jobs=-1)]: Done  23 out of  30 | elapsed:   19.1s remaining:    5.7s
[Parallel(n_jobs=-1)]: Done  27 out of  30 | elapsed:   21.2s remaining:    2.3s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   21.5s finished
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.0s


building tree 1 of 100building tree 2 of 100
building tree 3 of 100

building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100building tree 14 of 100
building tree 15 of 100
building tree 16 of 100

building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100building tree 21 of 100

building tree 22 of 100building tree 23 of 100

building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100

[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    0.1s



building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100

[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.4s



building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100building tree 63 of 100

building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100

[Parallel(n_jobs=-1)]: Done  69 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  82 tasks      | elapsed:    0.5s
[Parallel(n_jobs=-1)]: Done  96 out of 100 | elapsed:    0.6s remaining:    0.0s



building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100


[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    0.6s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight='balanced',
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=-1,
                                              oob_score=True, random_state=None,
                          

In [23]:
accuracy_score(y_test, rf.predict(X_test))

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done   9 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  16 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  25 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  45 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  56 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  69 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  82 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done  96 out of 100 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished


0.7595537621647283

# KNN

In [33]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 15, n_jobs = -1)

params = {
    "n_neighbors": np.arange(7, 14, 2),
}
knn = GridSearchCV(knn, params, n_jobs = -1, verbose = 10)

In [34]:
knn.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:   58.9s
[Parallel(n_jobs=-1)]: Done   8 out of  20 | elapsed:  1.1min remaining:  1.7min
[Parallel(n_jobs=-1)]: Done  11 out of  20 | elapsed:  2.4min remaining:  1.9min
[Parallel(n_jobs=-1)]: Done  14 out of  20 | elapsed:  2.5min remaining:  1.1min
[Parallel(n_jobs=-1)]: Done  17 out of  20 | elapsed:  2.8min remaining:   29.8s
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:  3.1min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:  3.1min finished


GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=-1,
                                            n_neighbors=15, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=-1,
             param_grid={'n_neighbors': array([ 7,  9, 11, 13])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=10)

In [36]:
accuracy_score(y_test, knn.predict(X_test))

0.9432411583194873

# Writing the knn model into file 

In [38]:
import pickle
filename = 'knn.sav'
pickle.dump(knn, open(filename, 'wb'))

# How to use model

### Loading the model using pickle

In [15]:
import pickle

filename = 'knn.sav'
loaded_model = pickle.load(open(filename, 'rb'))
# result = loaded_model.score(X_test, y_test)
# print(result)

### Create the list with answers then transform it to pandas DataFrame. After that ranspose it and send to "predict" method

In [47]:
# Example
import pandas as pd
import numpy as np

# INDICES_OF_THE_RESULT = {
#     0: '"Неизвестно"',
#     1: '"Не болеет"',
#     2: '"Болеет"'
# }

lst = [0, 1, 1, 1, 0, None, 1, 0]     ## list with data

lst = np.array(lst, dtype = float)
lst = np.nan_to_num(lst, nan = -1)

result = loaded_model.predict_proba([lst])[0]

# print(result)
print("Вероятность болезни составляет {}%".format(np.round(result[2]*100, 3)))


Вероятность болезни составляет 92.308%
